-- SmartCS Agent MySQL 8.0.12 enum enforcement patch
-- MySQL versions before 8.0.16 parse CHECK constraints but do not enforce them.
-- This script uses ENUM columns to enforce key finite-state fields.

USE `smartcs_agent`;

ALTER TABLE `cs_session`
    MODIFY COLUMN `status` ENUM('ACTIVE', 'HUMAN_TAKEOVER', 'TIMEOUT', 'CLOSED') NOT NULL DEFAULT 'ACTIVE' COMMENT '会话状态',
    MODIFY COLUMN `dialog_state` ENUM('INIT', 'INTENT_RECOGNIZED', 'SLOT_FILLING', 'READY_TO_EXECUTE', 'WAITING_CONFIRM', 'EXECUTING', 'EXECUTED', 'COMPLETED', 'HUMAN_REVIEW', 'HUMAN_TAKEOVER', 'TIMEOUT', 'CLOSED') NOT NULL DEFAULT 'INIT' COMMENT '对话状态，参考 DialogState 枚举';

ALTER TABLE `cs_message`
    MODIFY COLUMN `role` ENUM('USER', 'AGENT', 'HUMAN_AGENT', 'SYSTEM') NOT NULL COMMENT '消息角色',
    MODIFY COLUMN `message_type` ENUM('TEXT', 'IMAGE', 'FILE', 'CARD', 'ACTION', 'SYSTEM') NOT NULL DEFAULT 'TEXT' COMMENT '消息类型',
    MODIFY COLUMN `risk_level` ENUM('L0', 'L1', 'L2', 'L3') DEFAULT NULL COMMENT '风险等级',
    MODIFY COLUMN `route_decision` ENUM('AUTO_REPLY', 'AUTO_EXECUTE', 'CONFIRM_BEFORE_EXECUTE', 'HUMAN_REVIEW', 'HUMAN_TAKEOVER', 'REJECT') DEFAULT NULL COMMENT '路由决策';

ALTER TABLE `risk_decision`
    MODIFY COLUMN `risk_level` ENUM('L0', 'L1', 'L2', 'L3') NOT NULL COMMENT '风险等级',
    MODIFY COLUMN `route_decision` ENUM('AUTO_REPLY', 'AUTO_EXECUTE', 'CONFIRM_BEFORE_EXECUTE', 'HUMAN_REVIEW', 'HUMAN_TAKEOVER', 'REJECT') NOT NULL COMMENT '路由决策';

ALTER TABLE `work_order`
    MODIFY COLUMN `risk_level` ENUM('L0', 'L1', 'L2', 'L3') NOT NULL COMMENT '风险等级',
    MODIFY COLUMN `route_decision` ENUM('AUTO_REPLY', 'AUTO_EXECUTE', 'CONFIRM_BEFORE_EXECUTE', 'HUMAN_REVIEW', 'HUMAN_TAKEOVER', 'REJECT') NOT NULL COMMENT '触发工单的路由决策',
    MODIFY COLUMN `status` ENUM('PENDING', 'ASSIGNED', 'PROCESSING', 'APPROVED', 'REJECTED', 'RESOLVED', 'CLOSED', 'ESCALATED') NOT NULL DEFAULT 'PENDING' COMMENT '状态',
    MODIFY COLUMN `priority` ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NORMAL' COMMENT '优先级';

ALTER TABLE `work_order_action`
    MODIFY COLUMN `action_type` ENUM('CREATE', 'ASSIGN', 'APPROVE', 'REJECT', 'MODIFY_AND_APPROVE', 'TAKEOVER', 'ESCALATE', 'CLOSE') NOT NULL COMMENT '动作';

ALTER TABLE `skill_registry`
    MODIFY COLUMN `base_risk_level` ENUM('L0', 'L1', 'L2', 'L3') NOT NULL COMMENT '基础风险等级',
    MODIFY COLUMN `execution_type` ENUM('SYNC', 'ASYNC', 'REVIEW_ONLY') NOT NULL DEFAULT 'SYNC' COMMENT '执行类型',
    MODIFY COLUMN `status` ENUM('DRAFT', 'ACTIVE', 'DISABLED', 'DEPRECATED') NOT NULL DEFAULT 'DRAFT' COMMENT '状态';

ALTER TABLE `skill_slot`
    MODIFY COLUMN `slot_type` ENUM('STRING', 'NUMBER', 'BOOLEAN', 'ENUM', 'DATE', 'DATETIME', 'ADDRESS', 'PHONE', 'ORDER_ID', 'AMOUNT', 'JSON') NOT NULL COMMENT '槽位类型';

ALTER TABLE `skill_api_step`
    MODIFY COLUMN `http_method` ENUM('GET', 'POST', 'PUT', 'PATCH', 'DELETE') NOT NULL COMMENT 'HTTP 方法';

ALTER TABLE `skill_execution_log`
    MODIFY COLUMN `risk_level` ENUM('L0', 'L1', 'L2', 'L3') NOT NULL COMMENT '执行时风险等级',
    MODIFY COLUMN `route_decision` ENUM('AUTO_REPLY', 'AUTO_EXECUTE', 'CONFIRM_BEFORE_EXECUTE', 'HUMAN_REVIEW', 'HUMAN_TAKEOVER', 'REJECT') NOT NULL COMMENT '执行时路由决策',
    MODIFY COLUMN `status` ENUM('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REVIEW_REQUIRED', 'ROLLBACK_SUCCEEDED', 'ROLLBACK_FAILED') NOT NULL DEFAULT 'PENDING' COMMENT '执行状态';
