-- SmartCS Agent minimal risk rule seed data
-- This script is idempotent and can be safely re-run.

USE `smartcs_agent`;

INSERT INTO `risk_rule` (
    `rule_id`,
    `rule_name`,
    `intent_pattern`,
    `phase`,
    `condition_expr`,
    `target_risk_level`,
    `route_decision`,
    `action`,
    `priority`,
    `enabled`,
    `description`,
    `version`
) VALUES
(
    'R001_REFUND_REVIEW',
    '退款申请强制人工审核',
    'refund.apply',
    'PRE_EXECUTION',
    'intent == "refund.apply"',
    'L3',
    'HUMAN_REVIEW',
    'REVIEW',
    1000,
    1,
    '退款属于敏感资金操作，Agent 只收集信息并创建人工审核任务。',
    '1.0.0'
),
(
    'R002_EXCHANGE_REVIEW',
    '换货申请强制人工审核',
    'exchange.apply',
    'PRE_EXECUTION',
    'intent == "exchange.apply"',
    'L3',
    'HUMAN_REVIEW',
    'REVIEW',
    990,
    1,
    '换货涉及售后履约和库存处理，Agent 只收集信息并创建人工审核任务。',
    '1.0.0'
),
(
    'R003_LOW_CONFIDENCE_TAKEOVER',
    '低置信度转人工接管',
    NULL,
    'NLU',
    'nlu.confidence < 0.50',
    'L3',
    'HUMAN_TAKEOVER',
    'TAKEOVER',
    900,
    1,
    '意图识别置信度过低时，避免误操作，直接转人工。',
    '1.0.0'
),
(
    'R004_NEGATIVE_EMOTION_TAKEOVER',
    '异常情绪转人工接管',
    NULL,
    'GLOBAL',
    'emotion in ["ANGRY", "COMPLAINT", "THREATENING"]',
    'L3',
    'HUMAN_TAKEOVER',
    'TAKEOVER',
    880,
    1,
    '用户出现强烈负面情绪或投诉倾向时转人工安抚。',
    '1.0.0'
),
(
    'R005_HIGH_AMOUNT_REVIEW',
    '高金额操作人工审核',
    NULL,
    'PRE_EXECUTION',
    'amount >= 500.00 || refund_amount >= 500.00 || compensation_amount >= 100.00',
    'L3',
    'HUMAN_REVIEW',
    'REVIEW',
    850,
    1,
    '涉及高金额退款、补偿或敏感资金变动时进入人工审核。',
    '1.0.0'
),
(
    'R006_FREQUENT_OPERATION_TAKEOVER',
    '高频操作转人工接管',
    NULL,
    'GLOBAL',
    'user.intent_count_1h >= 3 || user.session_count_1h >= 5',
    'L3',
    'HUMAN_TAKEOVER',
    'TAKEOVER',
    820,
    1,
    '同一用户短时间内频繁触发敏感意图或会话，转人工确认风险。',
    '1.0.0'
),
(
    'R007_SHIPPED_ADDRESS_CONFIRM',
    '已出库地址修改需用户确认',
    'order.modify_address',
    'PRE_EXECUTION',
    'intent == "order.modify_address" && order.status in ["PAID", "PICKING", "SHIPPED"]',
    'L2',
    'CONFIRM_BEFORE_EXECUTE',
    'UPGRADE',
    700,
    1,
    '订单进入履约阶段后修改地址需要先让用户确认，后续可继续按订单状态升级人工审核。',
    '1.0.0'
),
(
    'R009_ORDER_CANCEL_CONFIRM',
    '取消订单需用户确认',
    'order.cancel',
    'PRE_EXECUTION',
    'intent == "order.cancel"',
    'L2',
    'CONFIRM_BEFORE_EXECUTE',
    'UPGRADE',
    740,
    1,
    '取消订单会变更订单状态，执行前必须由用户确认；真实退款不由 Agent 自动处理。',
    '1.0.0'
),
(
    'R008_SIGNED_ADDRESS_REJECT',
    '已签收订单禁止修改地址',
    'order.modify_address',
    'PRE_EXECUTION',
    'intent == "order.modify_address" && order.status == "SIGNED"',
    'L3',
    'HUMAN_REVIEW',
    'REVIEW',
    760,
    1,
    '已签收订单不能由 Agent 直接修改地址，需转人工判断后续处理方式。',
    '1.0.0'
)
ON DUPLICATE KEY UPDATE
    `rule_name` = VALUES(`rule_name`),
    `intent_pattern` = VALUES(`intent_pattern`),
    `phase` = VALUES(`phase`),
    `condition_expr` = VALUES(`condition_expr`),
    `target_risk_level` = VALUES(`target_risk_level`),
    `route_decision` = VALUES(`route_decision`),
    `action` = VALUES(`action`),
    `priority` = VALUES(`priority`),
    `enabled` = VALUES(`enabled`),
    `description` = VALUES(`description`),
    `version` = VALUES(`version`),
    `updated_at` = CURRENT_TIMESTAMP(3);
